### ISSUE TITLE
Tellstick Duo not detected

### ISSUE THREAD

**Issue by kenavn** [mliljedahl/telldus-core-alpine#1]
I run the docker container on Ubuntu 20.04 on ARM. I have tried just about anything getting the daemon to actually detect the USB device connected, but to no avail.

The telldusd process starts and reports nothing. I try sending "off" to the test device, and I am then informed that the process cannot find the Tellstick. 

Before I put a lot of work in describing the context a bit better; is there known problems running this docker container on a Ubuntu host? I have a suspicion this being related to USB, udev rules or such. I have explored all possible solutions in that area as well without luck.

**Comment by mliljedahl** [comment]
Thanks for reaching out @kenavn! This is tested on Ubuntu 20.04 amd64 so it might be an issue with ARM? I do not have any udev rues, just defaults and plugging in the tellstick duo in the usb port. Will try to see if I can find an arm device to test later today 👍

**Comment by mliljedahl** [comment]
@kenavn: I have now looked at this and when debugging telldus-core, fiddeling with udev rules and ARM it looks like you might not have the correct _tellstick.conf_. The tellstick.conf provided is the default one created by telldus-core.

I will include a snippet from my config, please do a backup of your current config and try that one and see if it solves the problem. You should then be able to run for example `docker exec -it telldus-core-alpine tdtool -f 1` and get back `Turning off device 1, livingroom-01 - Success`. The _serial_ in the config should be the same but you can verify that by running `sudo lsusb -v`.

```
user="root"
group="plugdev"
ignoreControllerConfirmation="false"

controller {
  id=1
  type=2
  serial="A7Z2Z64B"
}

device {
  id=1
  name="livingroom-01"
  protocol="arctech"
  model="selflearning-switch"
  parameters {
    house="1"
    unit="1"
  }
}
```
In one case I did have to run the container in _privileged_ mode which is not recommended but can be required depending on your setup. But try this as a last thing and to do so you need to edit your _docker-compose.yaml_ to something like this:

```
version: "3"
services:
  telldus-core-alpine:
    image: mliljedahl/telldus-core-alpine:1.0.1
    container_name: telldus-core-alpine
    restart: unless-stopped
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    volumes:
      - ./data/tellstick.conf:/etc/tellstick.conf:ro
    ports:
      - "50800:50800"
      - "50801:50801"
    privileged: true    
```
